---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
configMapGenerator:
  - name: lavalink-application
    files:
      - application.yml=config/application.yml
resources:
  - ./externalsecret.yaml
  - ./pod.yaml
  - ./service.yaml
