---
apiVersion: v1
kind: Service
metadata:
  name: lavalink
  labels:
    k8s-app: lavalink
spec:
  type: ClusterIP
  selector:
    k8s-app: lavalink
  ports:
    - name: lavalink
      port: 2333
      targetPort: lavalink
