apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:WrM4bl8mIFvatj/bSF6C3NeoKPa6VpXq2oYLqfh3cYjDL/X6JWV03A==,iv:068wLqq8NeLSx1H/9bEjpZ/8Z/nKVc6nU/sq7z/tCY4=,tag:UkcBfDr7twnDs1WCZEwuFg==,type:str]
sops:
  age:
    - recipient: age1ruelpf0ywylp4kctsy5ulz2kh76z0a9vkm0gmwss3k7srdpm33sqtf754j
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSM0Q5YisxNFpnWVBLWkN4
        QUczMUF1Y3RmNVR4dzBrOE5tRzdTU2RWSWdRCnh5eFhVSmhpKzVMZlBVZWFFZ0hC
        bnhVWXZnQVNONWxlT2dobHJrT1FOd1kKLS0tIG5EMi9OcGZYVk9ZSVNERmJiRHl6
        WTZldjV3cEt0UVhZbW9pT0VlRXRIOFUKB8kekMNf5mk7pQuNd5jBBR0qhgaAGAOD
        K0NF2XAKMHRm5qxe7kf45ZLV06qeGwWDiZy90PlVUJ5fqtJ80vL2og==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-19T06:53:43Z"
  mac: ENC[AES256_GCM,data:GORE80B1B9DdtTsC38aDB5QOOaPSxrX9xNFF8cbicRVKznmg4dc5KOEqzMXkC9psfgGmZYxqIEP9xMmwjyssa2QVPbQ8pkxbvzAt3IOvMkVf+QUbmrhkn0NkGpVsxjaUjbZ1PhaxkEV8VsSLh+eCC1OToj9bC/6vBzs5m8ls7p0=,iv:9USEtNJ25zXtoWwgJmVOo6FEMu0nktZ2WBclsYqm2mg=,tag:ADeLoicEw9Qbz8HaLspNQg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
