apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:daH55vLhov008MI=,iv:/6idrUmK7JFq04hdw778io1OTfxFJxduV3qwOSBO4kQ=,tag:3PQHIHccnhpi4lDyBB9v1A==,type:str]
    TEST_SECRET: ENC[AES256_GCM,data:ejinXyopOXs=,iv:UvnPjn5HnEjIuDi/yf1AKOZjN/R3uoz10GxN4wo4bz8=,tag:dpyYpNZtlM7OnnLNsDj+Sg==,type:str]
sops:
    age:
        - recipient: age1ruelpf0ywylp4kctsy5ulz2kh76z0a9vkm0gmwss3k7srdpm33sqtf754j
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXRVQwTno5b0h1THkxM3RJ
            b05wdjRGSS9rNDQvcmtMRkpGSVdDOWVNR2pRCmpYUmxjZGtRQ1hZY0R6eHBjcW05
            Q2prT1gvTFk5Q3djV3pkK094TitUdVkKLS0tIHZ6aEI3Y29ySDFsV0ZnSkd5cks0
            alhxMnBnL2FmR0dhQnNuaXFLa1Z3L2cK9dDwnv3QTIrSRhEVyiE0Xdk39c3LvhrA
            fbCSsjWHQwt6xsOja9qs2MhFbWL7eDxynShywkZx0GgACuyzvSeLmQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-18T03:53:12Z"
    mac: ENC[AES256_GCM,data:DgfQmoGwd4xPlaG8j+9YxASdirXZaFHNkQlWINg44D1q8bvXILjcDaE26F8QWIGYccws0ymVRQG611RrMMqjcl3QMYGqxvhl8nqfIaylgSimkMB6aQmPxhXOI13rRmyD66CFgK74vUsZ/OKSgQ0Zk7GVz+XBEoPsplcf0/KI3/U=,iv:Gl5mY4xJZ+jUwuy+id+/vgKvMhnXXW/UIyuSdy9kZuA=,tag:/BtEK0bgq46Ujnn8/67OLA==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.11.0
