apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:daH55vLhov008MI=,iv:/6idrUmK7JFq04hdw778io1OTfxFJxduV3qwOSBO4kQ=,tag:3PQHIHccnhpi4lDyBB9v1A==,type:str]
    BITWARDEN_ACCESS_TOKEN: ENC[AES256_GCM,data:UOL04m5t9iHSvngd3OW+ZN6eZOgXysorfhyvsA8x2QWi3jSca5qpQYmNjSnye4jBh4RycAjVRL4DcL1HRcGg9QQTsPufO8yiK5h/xXwKrCAQGsB4zY428l/RlEy/Yg==,iv:mGtSrHwIWLG54KhL/nsfqm2YLFEino5uSbo2/dLSl7c=,tag:5QeJeecj3/WSxG37P0/X1A==,type:str]
    BITWARDEN_ORG_ID: ENC[AES256_GCM,data:YhYw/Fekoq+jLhrncGIFjTBZGfhKckTqi1DtSspmU79gP5qZ,iv:xLbyeGHeRbmz7rIg5uPeo68yPUidQaWYeUq6+Jvsm58=,tag:n8ieyQNhCKGlkXAm+lHZkw==,type:str]
    BITWARDEN_PROJECT_ID: ENC[AES256_GCM,data:8gixjexNFNgWXd+2UMFTGXg936Qew6S+bL2E2WLgCvA7zDO6,iv:JJifMN2bzdXgnQNqQAHommCwlsEDw1YZKtH+6PrRB0s=,tag:PE/UokYZBgZMJyWJTtNgMw==,type:str]
sops:
    age:
        - recipient: age1ruelpf0ywylp4kctsy5ulz2kh76z0a9vkm0gmwss3k7srdpm33sqtf754j
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXRVQwTno5b0h1THkxM3RJ
            b05wdjRGSS9rNDQvcmtMRkpGSVdDOWVNR2pRCmpYUmxjZGtRQ1hZY0R6eHBjcW05
            Q2prT1gvTFk5Q3djV3pkK094TitUdVkKLS0tIHZ6aEI3Y29ySDFsV0ZnSkd5cks0
            alhxMnBnL2FmR0dhQnNuaXFLa1Z3L2cK9dDwnv3QTIrSRhEVyiE0Xdk39c3LvhrA
            fbCSsjWHQwt6xsOja9qs2MhFbWL7eDxynShywkZx0GgACuyzvSeLmQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-03T08:39:57Z"
    mac: ENC[AES256_GCM,data:5tyyxG8Cmi9qMyxoYNIEexgtAi19lXDc6bADKJqI2XhauEfYe/HzmoYTmHUZWUmMuizjgbAtwmzi0se5lSTXPRJyVFePHVA4oJZF5XvQKDGjIEACfdM2y29iUa7LjPTdgraBYr6SauhFJCZpSOSwmDCEQ4SPX/XPA9sn3PcSX6U=,iv:guzuIBxcVlcFb702tur4ps0ZQf35t68p8kTCFJEkzXM=,tag:BQsuBOUf0R5QeKdvMFvWRg==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.11.0
