apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:daH55vLhov008MI=,iv:/6idrUmK7JFq04hdw778io1OTfxFJxduV3qwOSBO4kQ=,tag:3PQHIHccnhpi4lDyBB9v1A==,type:str]
    BITWARDEN_ACCESS_TOKEN: ENC[AES256_GCM,data:Kave38gatX+/zFvZnYBNeOWjr90yqqR8JZ2BQf98xw+0aLtgvBma05xJjNbjFjM818red/Q5A/MagPPg0wygRYwlYPZC9MCUo5DJLQKNo+cVlP4CCfdhAc+w3MIniQ==,iv:jNTb3mgIWmRSetDWdVMfScorUt/17UFo3uY3Sh/SYMU=,tag:WMKHviXdbe6bFm3ICLWl9g==,type:str]
sops:
    age:
        - recipient: age1ruelpf0ywylp4kctsy5ulz2kh76z0a9vkm0gmwss3k7srdpm33sqtf754j
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXRVQwTno5b0h1THkxM3RJ
            b05wdjRGSS9rNDQvcmtMRkpGSVdDOWVNR2pRCmpYUmxjZGtRQ1hZY0R6eHBjcW05
            Q2prT1gvTFk5Q3djV3pkK094TitUdVkKLS0tIHZ6aEI3Y29ySDFsV0ZnSkd5cks0
            alhxMnBnL2FmR0dhQnNuaXFLa1Z3L2cK9dDwnv3QTIrSRhEVyiE0Xdk39c3LvhrA
            fbCSsjWHQwt6xsOja9qs2MhFbWL7eDxynShywkZx0GgACuyzvSeLmQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-30T09:44:16Z"
    mac: ENC[AES256_GCM,data:ef6/597rkPqKWy76WUa7RlfALjDyEXm+zeR0TCmitEOPIn5TyBxrcSodgm1EZgSUGDUyjoxkEbFuigE0HNd+LX841fT1c+HX6vC68jtKpS3UztBClRfG9CwxMnvgoGtX8Fzj2qFXk/J13E40sA+Bd5XK2CM8pX1hE3AXLXmcFH0=,iv:yBn4e1CLdX7IYXQayHDBGCBRgARyMKlFHsRAVjfqw2A=,tag:bxm2rlSucr5pGNYUDQSQyw==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.11.0
