apiVersion: v1
kind: Pod
metadata:
  name: test-pod2
  namespace: dummy
spec:
  containers:
    - name: test
      image: busybox
      command: ["sleep", "3600"]
      volumeMounts:
        - mountPath: /joe
          name: u-local-hostpath
  volumes:
    - name: u-local-hostpath
      hostPath:
        path: /var/mnt/local-hostpath