apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:s4CS6y61QHrKmdvbm83n7RMkDf1R5vb5mcQxbGJ/Fxk=,iv:7hdaNKarNt15Kp5U88RdXKVfa7gNkiRuWisUjtZn/Mw=,tag:ocV47qgXi+PtGpXxaFtbag==,type:str]
sops:
  age:
    - recipient: age1ruelpf0ywylp4kctsy5ulz2kh76z0a9vkm0gmwss3k7srdpm33sqtf754j
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDdWxMd1g2U0c3SUtMckZy
        cDFubnRHYXNiT0dDMW10QmlXMEVqWUg0YkhrCmZSMFl3SzBtY3FqbkllV3FMNlJz
        SGZMZUZwREF6S0RiUnNvMDBTM29RWVUKLS0tIHlLbjl3MEYvdS9rR210RXE4ckdL
        a0FlQXpZbjNGeW5mWklWOW5FeENONDAKkcff5IC0Ur/1g8w2gs1Jx7Xj58HnpZtI
        Ei+iEbPAbghpceDU3QDcXLL/ZvP3z03+XPVnBu/1t8eETOpbu22zXg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-19T06:53:43Z"
  mac: ENC[AES256_GCM,data:/irNlfVa9lleJk6lcMGgFdwvB1zwQxM+f2G+zOBcpWnh5RJxYbgL9OyuXo5TqWzRVBKG04oGAc0gidaf2aKIiQLsp8hGFKvsBBMQuw/NnIwaiIInS9eZVCt/Z7oq7gwrK2viWMUg9vR/rU02VFaxb8odlA2jc9GsVtyFtJmoXtA=,iv:oT6cIz7vFAChS0vaOazGGumusPlNaDZg5x0snc9UdsA=,tag:H9PA0zqY1Y47+R0cMpRnUA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
