apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:pW75izbsdnCiCtQAADqyMmYPnIevB/WynSLysjOpebyCwnrk5/WKmvKwzGF8qdV7UT6DACVNCq2GuHc8Zs8vJTdRR+7KEOjdeKzrMUxt34Z/39CD1KiyAlvkriAOMvkPtPk3TyZlzbD01i6VUO5M3MMfW0bB+eJsdkI/ASeYdSF3e6Es+2IJmKoPx2R3kTvRppagVSUoZX9IxkZ9Kl/PGC9oGz6ge1NFdFbx4gN3cCDyPzSm,iv:aNoWTDmcLgh23+t5t5KKnXIctct6O7vfJcubbSO76UI=,tag:MCBBtTQL1mWDy5O/mzXMfA==,type:str]
sops:
  age:
    - recipient: age1ruelpf0ywylp4kctsy5ulz2kh76z0a9vkm0gmwss3k7srdpm33sqtf754j
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzTWFQTzEvcEozQTdzQkRX
        RFlsdmpLUURrWkI4Qlh0YUg1NEdqSHl1MkhNCkNiSU5WdEpNSURRZXJDRjE5THR4
        NFJPelZQN1lUQ3FkVkFRRXo3OVhDcmcKLS0tIGk2YVZpSjVLemhENjdWR1AyY280
        cS9tdkhqY1lLcFZRbmV6bTdjKzE1ajAK8sR+T/mePzIySG6P6++DKNmG+VxkEE4T
        iVDlf+AaqTm3Ez5FKtloec/7Dr2YNo/XSmKlpXt7NXrL3n8SQnbC/A==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-19T06:53:43Z"
  mac: ENC[AES256_GCM,data:9jkbo2VNsNAfrhQcOluma46FqpGJvbBdF308xPg7KRhvRyJ/XG9lNXVtoYYbMgOQ/tbjWJRaUcFFF16G/41qYfYjYx+wRmSjM6btt6XzTnj6Z38VhpBNfmWNgrVtdBQCtb7VswW26rWM3O9bHopU9/gfiBpqMpR1Kntlrqb1qMg=,iv:mqK3Los2iGWfWyhkAaTyti7Q3s8LtIvie1FSIaOCp6s=,tag:vPL5Z6nITuAeCIAv4Er68w==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
