piVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ENC[AES256_GCM,data:JB/+1x64AUvA3sgz3/CChsmNHBUyvAD9ikSCn8Q3nYZZOaD50aQVSA==,iv:2gJ2rY2LFKNQgsa57vTkemrKGBbiDe36GW/NcCmtkUQ=,tag:SUmgEB1DEL/ilhzd1ghylg==,type:str]
sops:
    age:
        - recipient: age1ruelpf0ywylp4kctsy5ulz2kh76z0a9vkm0gmwss3k7srdpm33sqtf754j
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvUHlXaUoyMFJ6RlZRS1dD
            ZnRwYXZ4dlBVL09hWkNPODQ5VVFHNXVXdDBjCm0zdlZWQTBZNjJOOVhRb1lSOXda
            K2xJMTdXV0lwSC9YTTl4QUtkRzBMMjgKLS0tIDl4NVkrSDVmNHprM1BxK3EyVGNM
            SFZCcVZKVFE5ZHFrUGswTGZJMzZMd00KXYm4CRD60gmAMw/xeJ2V56EKYQ+sv0pd
            UiOJfGeLXC2DC+pz7Vsft9uLlo4mVp5w9ZYw0JJh+FzSsfRYRJwkgw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-31T07:35:09Z"
    mac: ENC[AES256_GCM,data:a/1kIGQKKyitJQvo25BlqmDkfQ4eETZnUMzyBOE/1GlqWCzYlAINS2rJ8RpIbmNUNGykG5qxE0/S/H42oqURhR/rl8xZBgUxzd8DGS6S54nCnfOKqBz/ZZZygJ9uebPwn1sv24Djkfu6zmVC/SisL0Jwse/wjfo8OZvSXR8sNng=,iv:rwC8aDUNrZBHcKWqLueMZ5idnfjyKk34DedgNgy5Ae0=,tag:Mcti4FdNVlw5fd0eFe2MkA==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.11.0
