apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:JB/+1x64AUvA3sgz3/CChsmNHBUyvAD9ikSCn8Q3nYZZOaD50aQVSA==,iv:2gJ2rY2LFKNQgsa57vTkemrKGBbiDe36GW/NcCmtkUQ=,tag:SUmgEB1DEL/ilhzd1ghylg==,type:str]
sops:
  age:
    - recipient: age1ruelpf0ywylp4kctsy5ulz2kh76z0a9vkm0gmwss3k7srdpm33sqtf754j
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvUHlXaUoyMFJ6RlZRS1dD
        ZnRwYXZ4dlBVL09hWkNPODQ5VVFHNXVXdDBjCm0zdlZWQTBZNjJOOVhRb1lSOXda
        K2xJMTdXV0lwSC9YTTl4QUtkRzBMMjgKLS0tIDl4NVkrSDVmNHprM1BxK3EyVGNM
        SFZCcVZKVFE5ZHFrUGswTGZJMzZMd00KXYm4CRD60gmAMw/xeJ2V56EKYQ+sv0pd
        UiOJfGeLXC2DC+pz7Vsft9uLlo4mVp5w9ZYw0JJh+FzSsfRYRJwkgw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-19T06:53:43Z"
  mac: ENC[AES256_GCM,data:U/fiB3DuiLSGWF9VM5E67Dw6HcFhmkWNwVfC3FxUPfzKIMDQjS4J7cnRk+4ZwjFeUMDK9bqQGFBkfB7uuTsjqS+WqOQSDe1r774eJxEyU2PKgziSep/TGloLl8S6aKy/IESn8itaMB5DLVEREciMVv+TaXMQ42hwmIbs0rST/i4=,iv:EhRt/YG20Gry5xZqC0tZ+0pppeKgpsMwC5cYOHKoz5A=,tag:7UWoPQ7xSZasfDOzq8gpxQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
