---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
configMapGenerator:
  - name: mongo-ensure-user
    files:
      - ensure-user.sh=config/ensure-user.sh
resources:
  - ./externalsecret.yaml
  - ./pvc.yaml
  - ./pod.yaml
  - ./service.yaml
