apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: bitwarden-test
  namespace: external-secrets
spec:
  refreshInterval: 1h
  secretStoreRef:
    # This name must match the metadata.name in the `SecretStore`
    name: bitwarden-login
    kind: SecretStore
  data:
  - secretKey: test
    remoteRef:
      key: "3b809ab9-ee54-4cd7-bdf3-b3e200a5afe2"
      property: value
