apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: bitwarden-test
  namespace: external-secrets
spec:
  refreshInterval: 1h
  secretStoreRef:
    # This name must match the metadata.name in the `SecretStore`
    name: bitwarden-login
    kind: SecretStore
  data:
  - secretKey: test
    remoteRef:
      key: "hello"
