---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: external-secrets
spec:
  chartRef:
    kind: OCIRepository
    name: external-secrets
  interval: 1h
  values:
    bitwarden-sdk-server:
      enabled: true
      extraVolumes:
        - name: tls
          secret:
            secretName: bitwarden-sdk-server-tls
      extraVolumeMounts:
        - name: tls
          mountPath: /tls
          readOnly: true
    leaderElect: true
    serviceMonitor:
      enabled: true
    grafanaDashboard:
      enabled: false
    webhook:
      replicaCount: 2