apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: bitwarden-login
spec:
  provider:
    bitwardensecretsmanager:
      auth:
        secretRef:
          accessToken:
            name: bitwarden-secrets
            key: BITWARDEN_ACCESS_TOKEN