apiVersion: v1
kind: Secret
metadata:
  name: bitwarden-secrets
stringData:
  BITWARDEN_ACCESS_TOKEN: ENC[AES256_GCM,data:ZjHJ/Gv4MPv1dv3Gzn/p6SqkcXaiA3yLK/ycLUB0Tz4sskMn0A+Cu9Rv+RpsCHKVQAEA8kbqA8EpAO00fJl+5P0tJQChITfy/D84V0TfG7k+zzsNccPPU/Ec2BEzGg==,iv:MVSZkShG+4FEYO8scN3IusTJ5D1i4IcSRer+Ma/xjnE=,tag:t+eC21z9YMRPHSHYRb5aTA==,type:str]
sops:
  age:
    - recipient: age1ruelpf0ywylp4kctsy5ulz2kh76z0a9vkm0gmwss3k7srdpm33sqtf754j
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2bWgvSDhhdHVPa2RaL1pa
        MEpZLy9uWWpWNG83Q2dOWjR2NmMrMTcwK1Q0CkVuQk5jdlgrR2pOa0xObWxDTG5j
        aTV5bVBFbDkxbWhNdXdCUWF5UW9SYjAKLS0tIEFCQ3l2QmU2eGVqNzNMdlB1RFhq
        QWZaeFZEbjNQWk1oTFB3YjdYc2ovY1kKDuou2WduZ5zfyon1XvjNkAZ5Hw3hE+3e
        iywUDrxsAFkm5NQt4QIff+x4XbICM0a4XFvHCgV81opIlkm0BIgZ7Q==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-31T06:29:37Z"
  mac: ENC[AES256_GCM,data:6XRq1yy30XlLm0a2lmQaXx1F7NAd+6INlMkRuF6aPIQ+BROs+kExjPP8BwR1kadsPYed/BO9kXIIq2reWc4dU3BPij+/YGt3dAXiuKsUwHDF5gPBO/Mk5Na+n++RKF3/mV9AlL4o9WV9dasUf9XCtuPC3UGw50+w1K6HuvaDxTg=,iv:QIQcCMXiaon7aiSK5wo6MZV9cMfXYcjiu0CAc2Py/ek=,tag:cewlLeRkjhnKWjSn4CEKfQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
