apiVersion: v1
kind: Secret
metadata:
    name: bitwarden-secrets
stringData:
    BITWARDEN_ACCESS_TOKEN: ENC[AES256_GCM,data:RIMNFZ2fZoFZcZq8nJFHpnMaanVP+Gvf2An7c1kVNWX8qUiut+5KcYbyDU+LXgQyj2nhY3nmzKWCKy38nNoy40YPJwz2s7+i/UVtketA1K3Gci8NBfgXiCl+wArnKg==,iv:PLa6MigA//wgOSJ67BARcp1D8TfxVs6DNY2soyPXihI=,tag:Eet+P8pztgoKU+Wec+EGdA==,type:str]
sops:
    age:
        - recipient: age1ruelpf0ywylp4kctsy5ulz2kh76z0a9vkm0gmwss3k7srdpm33sqtf754j
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2bWgvSDhhdHVPa2RaL1pa
            MEpZLy9uWWpWNG83Q2dOWjR2NmMrMTcwK1Q0CkVuQk5jdlgrR2pOa0xObWxDTG5j
            aTV5bVBFbDkxbWhNdXdCUWF5UW9SYjAKLS0tIEFCQ3l2QmU2eGVqNzNMdlB1RFhq
            QWZaeFZEbjNQWk1oTFB3YjdYc2ovY1kKDuou2WduZ5zfyon1XvjNkAZ5Hw3hE+3e
            iywUDrxsAFkm5NQt4QIff+x4XbICM0a4XFvHCgV81opIlkm0BIgZ7Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-03T10:38:40Z"
    mac: ENC[AES256_GCM,data:4tS+7MrfUPzXn5t/Tr+6WEIhDOuCrkEcAk9NhwGDZ+4HdIEhKtTLCamBlPIkwtDPY/f1AtTwYMBc3Cpgli9ttdSelevfx9/9i0uXWQKRHyyu7QlTx3I9BxD45OWYpxMMfNyVNTuxVo/9pwP33PaTV/zm5Dloou/09IL2i2bzvF4=,iv:GrWvM0bxwfDsKYooi11qCohV9E2OBSQNTObSbXNyU8c=,tag:5Z2OUNZ16G0rwiabAcXATQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.11.0
