apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: bitwarden-login
  namespace: external-secrets
spec:
  provider:
    bitwardensecretsmanager:
      auth:
        secretRef:
          accessToken:
            name: cluster-secrets
            key: BITWARDEN_ACCESS_TOKEN