apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: bitwarden-login
spec:
  provider:
    bitwardensecretsmanager:
      caProvider:
          type: Secret
          name: bitwarden-tls-certs
          key: ca.crt
          namespace: external-secrets
      auth:
        secretRef:
          credentials:
            name: cluster-secrets
            key: BITWARDEN_ACCESS_TOKEN
      organizationID: "${BITWARDEN_ORG_ID}"
      projectID: "${BITWARDEN_PROJECT_ID}"
      bitwardenServerSDKURL: https://bitwarden-sdk-server.external-secrets.svc.cluster.local:9998